class BuscarAnexo {
    constructor() {
        this.inversiones = [
            {A:'1',B:'NO',C:'PI-2151618: Sitio Arqueológico de Kuelap (Amazonas)',D:'ET/DE y Ejecución física',E:'EXPEDIENTE TECNICO',F:' -Con fecha 11AGO2020, se suscribió la Adenda 1 al Convenio de Cooperación Interinstitucional entre el Ministerio de Cultura y el Ministerio de Comercio Exterior y Turismo para la ejecución del componente, el cual tiene un costo de inversión de S/ 15,608,963 Millones.<br/> -Se registró la declaratoria de viabilidad el 05OCT2011, con el monto de inversión S/15,608,963.<br/> -Se tiene previsto la ejecución de la obra para el JUN2022.',G:' -Se viene desarrollando el Evaluación del tercer y último entregable del Expediente Técnico ',H:1450000,I:9584584},
{A:'1',B:'NO',C:'PI-2151618: Sitio Arqueológico de Kuelap (Amazonas)',D:'ET/DE y Ejecución física',E:'INFRAESTRUCTURA',F:' -Se tiene previsto la ejecución de la obra en JUN2022.<br/> -Actos preparatorios para el desarrollo del Expediente del PIA 2.',G:' - Elaboración de TDR para el desarrollo del Expediente del PIA 2, el mismo que contiene 3 entregables.<br/> -El costo de la ejecución de obra PIA 2 cuesta S/ 8,000,000; sin embargo, se está solicitando S/ 6,000,000 para el 2022 que corresponderían a los pagos por los entregables 1 al 6 y los entregables 6 al 14 pasarían al año 2023.',H:7624584,I:0},
{A:'1',B:'NO',C:'PI-2151618: Sitio Arqueológico de Kuelap (Amazonas)',D:'ET/DE y Ejecución física',E:'GESTION',F:' -Actos preparatorios para el desarrollo del Estudio Definitivo Plan de Manejo.<br/>  -OS Coordinación ',G:' -Elaboración de TDR para la elaboración del estudio de Plan de Manejo. 4 mese 3 entregables. <br/> -Actos preparatorios para iniciar el proceso de convocatoria',H:510000,I:0},
{A:'2',B:'NO',C:'IOARR-2430924: Huaca 26 (Lima)',D:'Ejecución física',E:'EJECUCION DE OBRA',F:' -CONTRATO Nº OO7-2O21-UE OO8 PROYECTOS ESPECIALES, de fecha 31AGO2021, se ejecuta la obra<br/> -La Obra se encuentra suspendida por haber viviendas que han construido en el terreno de la huaca',G:' -Reinicio de la Obra de la ejecución de la Obra.',H:331220,I:331220},
{A:'3',B:'NO',C:'IOARR-2430936: Huaca Caudivilla',D:'Ejecución física',E:'EJECUCION DE OBRA',F:' -Ejecución de Obra',G:' -Actualización de los costos del E.T<br/> -Lanzar el Proceso de Obra<br/> -Iniciar la ejecución de la Obra',H:266518,I:266518},
{A:'4',B:'NO',C:'PI-2131495: Lugar de la Memoria (LUM)',D:'ET/DE',E:'GESTIÓN',F:' -Gastos de Gestión',G:' -Implementación de la Gestión del Proyecto. Seguimiento y monitoreo',H:200000,I:1200000},
{A:'4',B:'NO',C:'PI-2131495: Lugar de la Memoria (LUM)',D:'ET/DE',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 30OCT2010, con el monto de inversión S/ 30,802,474.44<br/> -En proceso de elaboración de TDR para Diagnostico de la infraestructura y posterior elaboración de Saldo de ET',G:' -Estudio de Diagnostico para la Elaboración de E.T.',H:1000000,I:0},
{A:'5',B:'SI',C:'PI-2251549: Museo Nacional del Perú (MUNA)',D:'Ejecución física',E:'ADQUISICIÓN DE EQUIPAMIENTO Y MOBILIARIO',F:'  -Se registró la declaratoria de viabilidad el 06ENE2015, con el monto de inversión S/516,952,273<br/> -El componente infraestructura se culminó en DIC2020, se encuentra en proceso de recepción.<br/> -Mediante el Informe N° 115 -2015 -UE -PE -OP/OAER (09DIC2015), se brindó conformidad técnica al Expediente Técnico.<br/> -Con Resolución Jefatural N° 00058-2015-UE-PE/J (11DIC2015) se aprueba el Expediente Técnico con un presupuesto de S/278,699.06 y por un plazo de ejecución de (660) días calendario.',G:'  -Adquisición del mobiliario especializado etapa 2. la DA financiara el 50% de este mobiliario, el cual tiene un costo de S/ 22.5M. <br/> -Adquisición del mobiliario administrativo (Ejecución 2022). La DA financiara el 100% de este mobiliario, el cual tiene un costo de S/ 6M. ',H:17250000,I:18786967},
{A:'5',B:'SI',C:'PI-2251549: Museo Nacional del Perú (MUNA)',D:'Ejecución física',E:'GESTION',F:' -Gastos de Gestión',G:' -Gastos de Gestión: Pago Organismo Internacional, Equipo de Proyecto de Optimización y Mejora (POM) y equipo supervisor de la marcha blanca de la inversión.',H:1536967,I:0},
{A:'6',B:'SI',C:'PI-2446487: Ceviche',D:'Ejecución física',E:'EJECUCION DE OBRA',F:' -Este proyecto tiene 4 componentes: Adecuada investigación del ceviche como cocina tradicional peruana, (ii) Adecuado acondicionamiento para la interpretación cultural como expresión de la cocina peruana en la casa de la gastronomía peruana, (iii) Adecuadas tecnologías de información y comunicación vinculadas a la protección, conservación y difusión de los valores y significados del ceviche, y (iv) Eficiente gestión cultural a través de la comunicación, formación, difusión, entre otros.<br/> -Se registró la declaratoria de viabilidad el 10SET2019, con el monto de inversión S/ 2,456,499.99<br/> -Actualmente se encuentra en el desarrollo del componente 1: Adecuada investigación del ceviche como cocina tradicional peruana, que tiene como objetivo la postulación del ceviche a la lista representativa del patrimonio inmaterial UNESCO 2022.<br/> -Mediane el memorándum N° 001796 -2021 -OINV/MC (12NOV2021), se reitera la necesidad de contratación del servicio audiovisual para el proyecto Ceviche, se encuentra en proceso de convocatoria la contratación del servicio de producción audiovisual.',G:' -Desarrollo y ejecución del servicio de producción audiovisual (previsión adicional realizado en el 2021) cuyo monto adjudicado asciende a S/ 150,000.00; que correspondería a la entrega de 2 productos en   el año 2022, y culminaría en marzo 2022. <br/> -Desarrollo y ejecución de la elaboración del estudio definitivo de los componentes 2, 3 y 4 del PI, el cual comprendería de la presentación de 4 entregables que estaría culminando en NOV2022 como fecha tentativa.',H:550000,I:550000},
{A:'7',B:'SI',C:'IOARR-2456689: Batalla de Ayacucho (obelisco)',D:'Ejecución física',E:'INFRAESTRUCTURA',F:' -Se tiene previsto la ejecución de la obra para el ABR2022.',G:' -Elaboración de los términos de referencia en ENE2021.',H:2128110,I:2128110},
{A:'8',B:'SI',C:'IOARR-2456690: Batalla de Junín',D:'Ejecución física',E:'INFRAESTRUCTURA',F:' -Se tiene previsto la ejecución de la obra para el ABR2022.',G:' -Elaboración de los términos de referencia en ENE2021.',H:1491346,I:1491346},
{A:'9',B:'SI',C:'PI-2469016: Balcón de Huaura',D:'Ejecución física',E:'INFRAESTRUCTURA',F:' -Se tiene previsto la ejecución de la obra para el ABR2022.',G:' -Elaboración de los términos de referencia para la ejecución de obra ENE2021.',H:2776648,I:3399349},
{A:'9',B:'SI',C:'PI-2469016: Balcón de Huaura',D:'Ejecución física',E:'EXPEDIENTE TÉCNICO',F:' -Restructuración de TDR ENE2022',G:' -Elaboración de los estudios definitivos de los componentes 3, 4 y 5.',H:412701,I:0},
{A:'9',B:'SI',C:'PI-2469016: Balcón de Huaura',D:'Ejecución física',E:'GESTION',F:' -Gastos de Gestión',G:' -Administrador de contrato',H:210000,I:0},
{A:'10',B:'SI',C:'PI-2233917: Archivo General de la Nación (AGN)',D:'Ejecución física',E:'EJECUCION DE OBRA',F:' -En espera de la emisión de Resolución aprobada del ET del PI AGN.<br/> -En proceso de elaboración de TDR para lanzar a convocatoria el proceso de contratación de la ejecución de la obra.',G:' -Se desarrollará el proceso de convocatoria de la ejecución de la obra; el cual se estima que inicie en MAR2022 con valorizaciones periódicas conforme lo estipula el TDR.',H:20000000,I:39900000},
{A:'10',B:'SI',C:'PI-2233917: Archivo General de la Nación (AGN)',D:'Ejecución física',E:'SUPERVISION DE OBRA DE OBRA',F:' -En proceso de elaboración de TDR para lanzar a convocatoria el proceso de supervisión de la ejecución de la obra.',G:' -Se desarrollará el proceso de convocatoria para la supervisión de la ejecución de la obra; el cual se estima que inicie en MAR2022 con valorizaciones periódicas conforme lo estipula el TDR.',H:8900000,I:0},
{A:'10',B:'SI',C:'PI-2233917: Archivo General de la Nación (AGN)',D:'Ejecución física',E:'PLAN DE CONTINGENCIA',F:' -Debido a la persistencia del incumplimiento en la presentación del entregable completo por parte del consultor es que se determinó la resolución del contrato, notificándose al consultor de la decisión adoptada por la entidad.<br/> -En elaboración del TDR para la contratación de locales.',G:' -Elaboración de los TDR para el acondicionamiento y traslados de los bienes de DAI -AGN, los cuales generaran rentas mensuales durante el periodo fiscal 2022.<br/> -Asimismo, el monto estimado para la contratación del alquiler de locales asciende a 2.5MM.',H:9000000,I:0},
{A:'10',B:'SI',C:'PI-2233917: Archivo General de la Nación (AGN)',D:'Ejecución física',E:'GESTION',F:' -En proceso de devengado de 6 OS correspondiente a los especialistas del equipo de contingencia; a los cuales se les realizó pagos parciales por consecuencia de la resolución del contrato principal de consultoría de elaboración del Plan de Contingencia.',G:' -Contratación de servicios que apoyaran y acompañaran en el seguimiento del desarrollo del Plan de Contingencia, durante el desarrollo y ejecución del mismo.',H:2000000,I:0},
{A:'11',B:'SI',C:'PI-2320691: Museo Nacional de AAH (Pueblo Libre)',D:'Ejecución física',E:'PLAN DE CONTINGENCIA',F:' -Actualmente se encuentra a la espera de la autorización de Universidad Nacional Mayor de San Marcos para la intervención en el Lote N°08 donde se ejecutará el Estudios de Suelos para cerrar el Expediente Técnico y su posterior ejecución del Plan de contingencia (El Lote N°08 se encuentra dentro del MNAAHP)',G:' -Considerando que se apruebe en enero entonces en febrero se debe de Elaborar el TDR en febrero de 2022 para iniciar con la ejecución del Plan de Contingencia en junio del 2022',H:4166000,I:73266000},
{A:'11',B:'SI',C:'PI-2320691: Museo Nacional de AAH (Pueblo Libre)',D:'Ejecución física',E:'INFRAESTRUCTURA',F:' -En espera a la aprobación del ET para la Ejecución de la Infraestructura previsto para NOV del 2022',G:'<br/> -Elaboración de TDR el 15 ABRIL del 2022 para iniciar con el proceso de convocatoria, el inicio de la ejecución está programado aproximadamente el 07 de noviembre del 2021 <br/> -El monto programado para el 2022 es de S/52,500,000, el cual corresponde para el adelanto Directo y Adelanto de Materiales el 30% del monto total siendo la suma de (S/45,000,000) y 2 pagos de valorizaciones mes de Noviembre y Diciembre (7,500,000).',H:52500000,I:0},
{A:'11',B:'SI',C:'PI-2320691: Museo Nacional de AAH (Pueblo Libre)',D:'Ejecución física',E:'',F:' -En espera a la aprobación del ET para la ejecución de Restauración de la Infraestructura previsto para NOV del 2022',G:'<br/> -Elaboración de TDR el 15 ABRIL del 2022 para iniciar con el proceso de convocatoria, el inicio de la ejecución está programado aproximadamente el 07 de noviembre del 2021<br/> -El monto programado para el 2022 es de S/13,900,000, el cual corresponde para el adelanto Directo y Adelanto de Materiales el 30% del monto total siendo la suma de  (S/12,000,000) y 2 pagos de valorizaciones mes de Noviembre y Diciembre (1,900,000)',H:13900000,I:0},
{A:'11',B:'SI',C:'PI-2320691: Museo Nacional de AAH (Pueblo Libre)',D:'Ejecución física',E:'SUPERVISION DE OBRA',F:'Supervisión de Obra previsto para NOV del 2022',G:'<br/> -Elaboración de TDR el 15 ABRIL del 2022 para iniciar con el proceso de convocatoria<br/> -El monto programado para el 2022 es de S/2,700,000, el cual corresponde para el pago de 2 valorizaciones (Noviembre y Diciembre)',H:2700000,I:0},
{A:'12',B:'NO',C:'PI-2413312: Necrópolis de Ancón',D:'ET/DE y Ejecución física',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 09ABR2019, con el monto de inversión S/ 3,246,084.85<br/> -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la elaboración del ET/ED.',G:' -Se estima que la elaboración del ET/ED se realice en 3 productos, cuyo monto actualizado corresponde a S/250,000.00',H:250000,I:1213764},
{A:'12',B:'NO',C:'PI-2413312: Necrópolis de Ancón',D:'ET/DE y Ejecución física',E:'INFRAESTRUCTURA',F:' -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria 2022.',G:' -El inicio de la ejecución de la se estima que se realice en 2 años, el cual iniciaría en JUN2022, abarcando el pago de 6 valorizaciones aproximadamente en el año 2022.',H:952514,I:0},
{A:'12',B:'NO',C:'PI-2413312: Necrópolis de Ancón',D:'ET/DE y Ejecución física',E:'GESTION',F:' -Se encuentra en desarrollo la elaboración de términos de referencias del servicio de consultoría para el ET del proyecto.',G:'La contratación de un profesional especializado para otorgar seguimiento a la elaboración del desarrollo del ET',H:11250,I:0},
{A:'13',B:'SI',C:'IOARR-2491061: Casa Cultural Tupac Amaru (Cusco)',D:'ET/DE y Ejecución física',E:'EXPEDIENTE TECNICO',F:' -Se registró la aprobación de la IOARR fue el 14JUL2020, con el monto de inversión S/ 1,606,439.00<br/> -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la elaboración del ET/ED.',G:' -Se estima que la elaboración del ET/ED se realice en 3 productos.',H:187500,I:987500},
{A:'13',B:'SI',C:'IOARR-2491061: Casa Cultural Tupac Amaru (Cusco)',D:'ET/DE y Ejecución física',E:'EJECUCION DE OBRA',F:' -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la ejecución de la IOARR.',G:' -El componente a realizar será la remodelación de la sala de exposición y adquisición de museografía, cuya ejecución se estima que comprenda de 5 productos que iniciarían aproximadamente en JUN2022.',H:800000,I:0},
{A:'14',B:'NO',C:'IOARR-2497501: Mateo Salao (Lima)',D:'ET/DE y Ejecución física',E:'EXPEDIENTE TECNICO',F:' -Se registró la aprobación de la IOARR fue el 09SET2021, con el monto de inversión S/ 1,016,585.38.<br/> -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la elaboración del ET/ED.',G:' -Se estima que la elaboración del ET/ED se realice en 2 productos, por S/ 240,000.00 y S/60,000.00',H:300000,I:670000},
{A:'14',B:'NO',C:'IOARR-2497501: Mateo Salao (Lima)',D:'ET/DE y Ejecución física',E:'EJECUCION DE OBRA',F:' -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la ejecución de la IOARR.',G:' -El componente a realizar será la construcción del cerco perimétrico, cuya ejecución se estima que se dé con la presentación de 5 productos para los 2022 y 4 productos pasarían al año 2023',H:370000,I:0},
{A:'15',B:'SI',C:'PI-2505984: Gran Biblioteca Pública (Lima)',D:'Ejecución física',E:'GESTIÓN',F:' -Gastos de Gestión',G:' -Implementación de la Gestión del Proyecto. Seguimiento y monitoreo',H:650363,I:9919793},
{A:'15',B:'SI',C:'PI-2505984: Gran Biblioteca Pública (Lima)',D:'Ejecución física',E:'EJECUCION DE OBRA',F:' -Ejecución de Obra',G:' -Continuar con la ejecución de la Obra (Adelanto directo y adelanto de materiales).',H:9269430,I:0},
{A:'16',B:'SI',C:'PI-2506071: Casa Hacienda Punchauca (Lima)',D:'Ejecución física',E:'GESTIÓN',F:' -Gastos de Gestión',G:' -Implementación de la Gestión del Proyecto. Seguimiento y monitoreo',H:136152,I:3389381},
{A:'16',B:'SI',C:'PI-2506071: Casa Hacienda Punchauca (Lima)',D:'Ejecución física',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 06ENE2021, con el monto de inversión S/ 12,657,455.65<br/> -En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E. T',G:' -Estudio de Elaboración de E. T',H:453781,I:0},
{A:'16',B:'SI',C:'PI-2506071: Casa Hacienda Punchauca (Lima)',D:'Ejecución física',E:'EJECUCION DE OBRA',F:'Ejecución de Obra',G:' -Elaboración de los TDR<br/> -Convocatoria<br/> -Inicio de Ejecución de Obra (Adelanto Directoy Materiales)',H:2799448,I:0},
{A:'17',B:'NO',C:'PI-2506435: Hotel Comercio (Lima)',D:'ET/DE y Ejecución física',E:'GESTIÓN',F:' -Se registró la declaratoria de viabilidad el 19DIC2020, con el monto de inversión S/ 19,028,874.07<br/> -En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E. T',G:' -Implementación de la Gestión del Proyecto. Seguimiento y monitoreo',H:150000,I:4733439},
{A:'17',B:'NO',C:'PI-2506435: Hotel Comercio (Lima)',D:'ET/DE y Ejecución física',E:'EXPEDIENTE TECNICO',F:'',G:' -Convocatoria<br/> -Inicio de Elaboracion del E.T',H:1007522,I:0},
{A:'17',B:'NO',C:'PI-2506435: Hotel Comercio (Lima)',D:'ET/DE y Ejecución física',E:'EJECUCION DE OBRA',F:' -Ejecución de Obra',G:' -Elaboración de los TDR<br/> -Convocatoria<br/> -Inicio de Ejecución de Obra (Adelanto Directoy Materiales)',H:3575917,I:0},
{A:'18',B:'SI',C:'PI-2508807: I.C. (Nasca y Palpa)',D:'ET/DE',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 11ENE2021, con el monto de inversión S/ 23,033,381.84<br/> -En proceso de mejora del TDR para lanzar a convocatoria de elaboración de PEA',G:' -Elaboración del PEA',H:487060,I:487060},
{A:'19',B:'SI',C:'PI-2508852: Digitalización del AGN',D:'ET/DE',E:'GESTIÓN',F:' -Se registró la declaratoria de viabilidad el 13ENE2021, con el monto de inversión S/ 45,460,184.24.',G:' -Seguimiento del Proyecto',H:272716,I:2195432},
{A:'19',B:'SI',C:'PI-2508852: Digitalización del AGN',D:'ET/DE',E:'EXPEDIENTE TECNICO',F:' -En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E.T',G:' -Elaboración del TDR para la elaboración del Expediente Técnico<br/> -Lanzamiento de proceso<br/> -Desarrollo del E.T',H:1922716,I:0},
{A:'20',B:'SI',C:'PI-2498277: PB-Puno',D:'CAR',E:'INFRAESTRUCTURA',F:' -Ejecución de Obra',G:' -Actos preparatorios para la ejecución de Obra',H:15966775,I:15966775},
{A:'21',B:'SI',C:'PI-2498554: PB-San Martin',D:'CAR',E:'INFRAESTRUCTURA',F:' -Ejecución de Obra',G:' -Actos preparatorios para la ejecución de Obra',H:11864507,I:11864507},
{A:'22',B:'SI',C:'PI-2499924: PB-Junin',D:'CAR',E:'INFRAESTRUCTURA',F:' -Ejecución de Obra',G:' -Actos preparatorios para la ejecución de Obra',H:13034073,I:13034073},
{A:'23',B:'SI',C:'PI-2498131: PB-Cajamarca',D:'CAR',E:'INFRAESTRUCTURA',F:' -Ejecución de Obra',G:' -Actos preparatorios para la ejecución de Obra',H:12649944,I:12649944},
{A:'24',B:'SI',C:'PI-2498378: PB-Cusco',D:'CAR',E:'INFRAESTRUCTURA',F:' -Ejecución de Obra',G:' -Actos preparatorios para la ejecución de Obra',H:12361388,I:12361388},
{A:'25',B:'SI',C:'PI-2498352: PB-Amazonas',D:'CAR',E:'INFRAESTRUCTURA',F:' -Ejecución de Obra',G:' -Actos preparatorios para la ejecución de Obra',H:12788322,I:12788322},
{A:'26',B:'SI',C:'PI-2497434: PB-Ancash',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 11SET2020, con el monto de inversión S/ 13,578,390.27',G:' -Elaboración de E.T',H:817579,I:817579},
{A:'27',B:'SI',C:'PI-2499858: PB-Piura',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 07OCT2020, con el monto de inversión S/ 20,882,267.86',G:' -Elaboración de E.T',H:568477,I:568477},
{A:'28',B:'SI',C:'PI-2499997: PB-Ayacucho',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 14OCT2020, con el monto de inversión S/ 30,006,599.63',G:' -Elaboración de E.T',H:301830,I:301830},
{A:'29',B:'SI',C:'PI-2498610: PB-Ucayali',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 29SET2020, con el monto de inversión S/14,286,800.50',G:' -Elaboración de E.T',H:817579,I:817579},
{A:'30',B:'SI',C:'PI-2499914: PB-Arequipa',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 08OCT2020, con el monto de inversión S/20,297,262.46',G:' -Elaboración de E.T',H:582706,I:582706},
{A:'31',B:'SI',C:'PI-2498188: PB-Lambayeque',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 10OCT2020, con el monto de inversión S/16,932,205.02',G:' -Elaboración de E.T',H:663283,I:663283},
{A:'32',B:'SI',C:'PI-2498659: PB-Loreto',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 29SET2020, con el monto de inversión S/17,299,260.64',G:' -Elaboración de E.T',H:662360,I:662360},
{A:'33',B:'SI',C:'PI-2498268: PB-Huanuco',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 08OCT2020, con el monto de inversión S/14,831,659,40',G:' -Elaboración de E.T',H:662358,I:662358},
{A:'34',B:'SI',C:'PI-2498369: PB-Apurimac',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 09OCT2020, con el monto de inversión S/20,167,137.23',G:' -Elaboración de E.T',H:560977,I:560977},
{A:'35',B:'SI',C:'PI-2499921: PB-Tumbes',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 08OCT2020, con el monto de inversión S/11,519,369.55',G:' -Elaboración de E.T',H:474242,I:474242},
{A:'36',B:'SI',C:'PI-2499859: PB-Ica',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 07OCT2020, con el monto de inversión S/14,105,820.39',G:' -Elaboración de E.T',H:474242,I:474242},
{A:'37',B:'SI',C:'PI-2499288: PB-Tacna',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 07OCT2020, con el monto de inversión S/14,832,554.84',G:' -Elaboración de E.T',H:479906,I:479906},
{A:'38',B:'SI',C:'PI-2498138: PB-Callao',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 30SET2020, con el monto de inversión S/20,662,539.54',G:' -Elaboración de E.T',H:674965,I:674965},
{A:'39',B:'SI',C:'PI-2498147: PB-La Libertad',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 30SET2020, con el monto de inversión S/14,754,954.82',G:' -Elaboración de E.T',H:465397,I:465397},
{A:'40',B:'SI',C:'PI-2498275: PB-Huancavelica',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 10OCT2020, con el monto de inversión S/15,941,850.42',G:' -Elaboración de E.T',H:624697,I:624697},
{A:'41',B:'SI',C:'PI-2497468: PB-Huacho (Lima)',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 12SET2020, con el monto de inversión S/15,092,412.77',G:' -Elaboración de E.T',H:465396,I:465396},
{A:'42',B:'SI',C:'PI-2497656: PB-Moquegua',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 11SET2020, con el monto de inversión S/16,332,550.60',G:' -Elaboración de E.T',H:479907,I:479907},
{A:'43',B:'SI',C:'PI-2498259: PB-Pasco',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 09OCT2020, con el monto de inversión S/14,403,937.59',G:' -Elaboración de E.T',H:568057,I:568057},
{A:'44',B:'SI',C:'PI-2498370: PB-Madre De Dios',D:'CAR',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 29SET2020, con el monto de inversión S/13,506,354.16',G:' -Elaboración de E.T',H:662360,I:662360},
{A:'45',B:'SI',C:'PI-2505980: Parque Lineal Pachacamaq',D:'ET/DE',E:'EXPEDIENTE TECNICO',F:' -Se registró la declaratoria de viabilidad el 10DIC2020, con el monto de inversión S/ 24,126,075.80.<br/> -Con memorándum Nº 1996 -2021 -OINV (01DIC2021) se solicitó la desestimación del proceso de contratación del servicio de consultoría para la elaboración del PEA, toda vez que no se cuenta con recursos presupuestales para el financiamiento del proceso en el presente año fiscal, y este dependerá a su vez de la demanda adicional que se otorgue el siguiente periodo fiscal',G:' -Se remitirá el TDR actualizado para la contratación del servicio de consultoría de la elaboración del PEA.<br/> -Se comenzará a ejecutar la elaboración del proyecto de evaluación arqueológica (PEA), el cual comprende 7 productos en un plazo de 250 días calendarios.',H:1259939,I:1259939},
{A:'46',B:'',C:'Estudios de Preinversión',D:'',E:'ESTUDIOS DE PREINVERSIÓN',F:' -16 Estudios de Preinversión',G:' -Elaboración de Estudios de Preinversión',H:3350000,I:3350000},
{A:'TOTAL',B:'',C:'',D:'',E:'',F:'',G:'',H:268781729,I:268781729},



        ];
        this.inversionesBK = this.inversiones;
        this.onInit();
        console.log(this.inversiones);
    }
    onInit() {
        let bodyAnexo = document.getElementById("bodyAnexo");
        while (bodyAnexo.rows.lenght > 0) {
            bodyAnexo.deleteRow(0);
        }
        this.inversiones.forEach(inversion => {
            let fila = bodyAnexo.insertRow(bodyAnexo.rows.lenght);
            fila.insertCell(0).innerHTML = inversion.A;
            fila.insertCell(1).innerHTML = inversion.B;
            fila.insertCell(2).innerHTML = inversion.C;
            fila.insertCell(3).innerHTML = inversion.D;
            fila.insertCell(4).innerHTML = inversion.E;
            fila.insertCell(5).innerHTML = inversion.F;
            fila.insertCell(6).innerHTML = inversion.G;
            fila.insertCell(7).innerHTML = inversion.H.toLocaleString('ENG');
            fila.insertCell(8).innerHTML = inversion.I.toLocaleString('ENG');

              
        });
    }
        
}

let busqueda = new BuscarAnexo();


function myFunction() {
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("valor");
    filter = input.value.toUpperCase();
    table = document.getElementById("bodyAnexo");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[2];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }       
    }
  }