class BuscarAnexo {
  constructor() {
    this.inversiones = [

      {'A':'1','B':'NO','C':'PI - 2151618: Sitio Arqueológico de Kuelap (Amazonas)','D':'ET/DE y Ejecución física','E':'EXPEDIENTE TECNICO','F':'* Con RM N° 091-2020-MC, de fecha 04MAR2020, se encargó a la UE 008 del MINCUL, la ejecución del PI con CUI N° 2151618<br>* Con fecha 11FEB2020, se suscribió el Convenio de Cooperación Interinstitucional, entre el MINCUL y MINCETUR para la ejecución de recuperación de los recursos turísticos – Restauración Kuélap, cuyo componente tiene un costo de inversión de S/15,608,963.<br>* Se cuenta con Contrato N° 020-2020-UE008 PROYECTOS ESPECIALES, por la elaboración del ET/DE.<br>* Se está evaluando la posibilidad de resolver el contrato con la empresa NEFASA S.A.C., toda vez que el contratista no estaría cumpliendo con sus obligaciones contractuales de manera oportuna.<br>*Asimismo, de acuerdo a ley se ha vuelto a enviar al segundo postor del concurso público por la elaboración del ET/DE, a fin de que continue con la elaboración del ET/DE, correspondiente al 3er y ultimo entregable por un monto de S/538,056.00','G':'* La DA, financiará el 3er y ultimo entregable del Contrato N° 020-2020-UE00 por la elaboración del ET/DE por un monto de S/538,056<br>* Supervisión del ET/DE por un monto de S/54,000.00','H':592056,'I':1712056,},
      {'A':'1','B':'NO','C':'PI - 2151618: Sitio Arqueológico de Kuelap (Amazonas)','D':'ET/DE y Ejecución física','E':'GESTIÓN','F':'* En el marco del convenio suscrito entre el MINCUL y MINCETUR, se vienen contratando servicios de: i) seguimiento y monitoreo a la ejecución del PI, ii) servicios por especialidades de los entregable 1 y 2 del ET/DE, iii) Servicios de mantenimiento y vigilancia del sitio arqueológico, y iv) servicio de un arqueólogo para delimitación y diagnóstico del terreno. <br>* Adquisidores varios en la conservación de sito hacia la intervención física de la obra.<br>* Servicios varios en el marco del desarrollo de la ejecución del componente Restauración Kuelap','G':'* Servicios de seguimiento y gastos indirectos derivados de la ejecución del proyecto S/120,000','H':120000,'I':1712056,},
      {'A':'1','B':'NO','C':'PI - 2151618: Sitio Arqueológico de Kuelap (Amazonas)','D':'ET/DE y Ejecución física','E':'INFRAESTRUCTURA','F':'* Ejecución de Obra','G':'Ejecución de obra del acceso 1 a la bóveda ','H':1000000,'I':1712056,},
      {'A':'2','B':'NO','C':'IOARR - 2430936: Huaca Caudivilla','D':'Ejecución física','E':'EJECUCION DE OBRA','F':'* Se aprobó el Expediente Técnico de la IOARR Caudivilla con la Resolución Jefatural N° 014-2021-UE-PE/J','G':'* Se dará inicio a la ejecución de la obra con un monto estimado de S/234,570.00<br>* La supervisión de obra tiene un costo estimado de S/20,000.00<br>* El Plan de Monitoreo Arqueológico (PMA) S/18,000.00<br>* Sensibilización social por un monto de S/5,118.00','H':277688,'I':277688,},
      {'A':'3','B':'NO','C':'PI - 2131495: Lugar de la Memoria (LUM)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':'* Se registró la declaratoria de viabilidad el 30OCT2010, con el monto de inversión S/ 30,802,474.44<br>* Con RM N° 486-2019-MC, de fecha 25NOV2019, encargan al MINCUL a través de la UE 008 el PI LUM. <br>* Se ha convocado el servicio de Diagnostico, Evaluación, Análisis y Estudio de riesgos estructurales para la edificación del Lugar de la Memoria, cuyo procedimiento de selección de la Adjudicación Simplificada 001-2021-UE008-PE-2 fue declarado desierto en su segunda convocatoria al año 2021.','G':'* Se convocará el DE para el estudio de Diagnostico (determinar las fallas estructurales del PI), elaboración del ET/DE S/300,000','H':300000,'I':350000,},
      {'A':'3','B':'NO','C':'PI - 2131495: Lugar de la Memoria (LUM)','D':'ET/DE','E':'GESTIÓN','F':'* Gastos de Gestión','G':'* Contratación del servicio de diagnóstico, evaluación y análisis de estudios de riesgos estructurales S/50,000.00','H':50000,'I':350000,},
      {'A':'4','B':'SI','C':'PI - 2251549: Museo Nacional del Perú (MUNA)','D':'Ejecución física','E':'ADQUISICIÓN DE EQUIPAMIENTO Y MOBILIARIO','F':'* Se registró la declaratoria de viabilidad el 06ENE2015, con el monto de inversión S/516,952,273<br>* El componente infraestructura se culminó en DIC2020, se encuentra en proceso de recepción.<br>*Con fecha 14ABR2015, la UNOPS y el MINCUL suscribieron un Convenio de Cooperación Interinstitucional, con el objeto de prestar servicios de Asistencia Técnica bajo la modalidad de Administración de Recursos para el “Mejoramiento Integral del Servicio de Interpretación del Patrimonio Cultural mediante la creación del Museo Nacional del Perú en el distrito de Lurín, Lima.<br>*Con Resolución N° 00011-2021-UE-PE/J de fecha 26MAR2021, se designó al comité de Recepción de Obra.<br>*Obra Complementaria “Sistema de Media Tensión” culminada.<br>*Obra Complementaria “Sistema de Abastecimiento y Agua Potable” en arbitraje<br>• Con fecha 15JUN2021 se culminó con la recepción de las áreas priorizadas las mismas que se encuentra en proceso de definición de las actas de recepción.<br>* Se cuenta con contrato suscrito por la elaboración del Programa de Difusión y Comunicaciones, en el marco del Plan Museológico.<br>* En proceso de elaboración de los Términos de Referencia para el proceso de Liquidación de Obra.<br>* En el marco de la ejecución de la inversión, se vienen convocando los procesos de limpieza, seguridad y vigilancia del Museo.<br>* Con fecha 21JUL2021 se firmó el contrato del Mobiliario especializado Etapa 1 para el MUNA.<br>• En proceso de elaboración de los Términos de Referencia para el proceso del Mobiliario Especializado Etapa 2 y Mobiliario Administrativo, por parte del área usuaria (DGM).<br>* Se encuentra en proceso de recepción de la obra principal Sección 2.<br> ','G':' -Culminación del Expediente Técnico NOV2015.<br> - Ejecución de obra 2016 -2020<br> - En proceso de ejecución del Plan Museológico hasta el 2024.<br> - Adquisición del Mobiliario especializado etapa 2  (Ejecución 2022).<br> - Adquisición del mobiliario administrativo (Ejecución 2022).<br> - Servicio de Liquidación para la obra principal (Ejecución 2022).<br> - Adquisición de proyector para el auditorio del MUNA (Ejecución 2022).<br> - Proceso para la elaboración del Guion Museográfico de la exposición permanente del MUNA  (Ejecución 2022).<br> -Servicio de Limpieza y fumigación para el MUNA  (Ejecución 2022).  <br> - Servicio de seguridad y vigilancia para el MUNA (Ejecución 2022). <br>La demanda adicional financiera el mobiliario especializado, el cual tiene un costo de S/22,000,000.00, con un plazo de ejecución de 10 meses; sin embargo, para el 2022 se requiere S/11,000,000.  <br>*Asimismo, la demanda adicional financiera el mobiliario administrativo, el cual tiene un costo de inversión de S/6,000,000.','H':17000000,'I':17000000,},
      {'A':'5','B':'SI','C':'PI - 2446487: Ceviche','D':'Ejecución física','E':'EJECUCION','F':'* Se registró la declaratoria de viabilidad el 10SET2019, con el monto de inversión S/ 2,456,499.99<br>* En desarrollo del Componente 1: Adecuada investigación del ceviche como cocina tradicional peruana. <br>* Se ha presentado ante la UNESCO para la candidatura para ser incluidos en el patrimonio inmaterial UNESCO 2022.','G':'* Estudio de mercado para desarrollo de los TdR<br>* Ejecución de los componentes 2,3 y 4 del PI por un costo total de S/452,092.00<br>* Componente 2: Adecuado acondicionamiento para la interpretación cultural del ceviche como expresión de la cocina tradicional en la casa de gastronomía <br>* Componente 3: Adecuadas tecnologías de información y comunicación vinculadas a la protección, conservación y difusión de los valores significados del ceviche <br>* Componente 4: Eficiente gestión cultural a través de la comunicación, formación, difusión entre otros','H':452092,'I':452092,},
      {'A':'6','B':'SI','C':'PI - 2469016: Balcón de Huaura','D':'ET/DE y Ejecución física','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 17MAY2016, con el monto de inversión S/16,012,012<br> * En el 2022, se tiene previsto volver a convocar el servicio de consultoría para la elaboración de estudios definitivos de los componentes 3,4 y 5 del proyecto de inversión<br>* Se cuenta con ET/DE de infraestructura ','G':' - En proceso aprobación del ET/DE de obra mediante Acto Resolutivo por parte de la UE 008.<br> - Se lanzará el proceso de desarrollo del Estudios Definitivos de los Componentes 3, 4 y 5. (ET/DE Museografía) S/420,000.00','H':420000,'I':4720000,},
      {'A':'6','B':'SI','C':'PI - 2469016: Balcón de Huaura','D':'ET/DE y Ejecución física','E':'INFRAESTRUCTURA','F':'* Ejecución de Obra','G':'Ejecución de obra (infraestructura)','H':4300000,'I':4720000,},
      {'A':'7','B':'SI','C':'PI - 2233917: Archivo General de la Nación (AGN)','D':'Ejecución física','E':'PLAN DE CONTINGENCIA','F':'* Con fecha 09/07/2017 se declaró la viabilidad del PI <br>* Cuenta con un costo actualizado de S/192,909,328.42<br>* Con RM N° 096-2019-MC, de fecha 11MAR2019, se encarga a la UE 008 el PI con CUI N° 2233917.<br>* Se cuenta con la elaboración de la Línea Base (CONTRATO N° 001-2021-UE008 PE por un monto de S/ 140.000.00)<br>* Se suscribo el CONTRATO N° 002-2021-UE008 PE por un monto de S/515,055.32 para la elaboración del Plan de Contingencia <br>* Se cuenta con CONTRATO N° 006-2020-UE008 PE por la elaboración del ET/DE por un monto de S/4,453,740.02 y su supervisión con CONTRATO N° 007-2020-UE008 PE por el monto de S/1,327,571.04.<br>* Del Contrato N° 006-2020-UE008 PE, a la fecha, se cuenta con 4 entregables con conformidad y en elaboración del 5to entregable, el mismo que está cubriéndose con una previsión de recursos, con cargo a recursos de inversiones de la UE 008<br>* Se ha venido contratando servicios de seguimiento y monitoreo a la ejecución del PI.<br>* Servicios por especializades en el marco de la ejecución del PI <br>* Se contrato el servicio para el Plan de Contingencia (alquiler de locales, adecuación de local, traslado de archivos); sin embargo, este contrato fue resulto porque no se llegaron a acuerdo por el primer producto que es de alquileres de locales','G':'Se requiere dar inicio a la implementación del Plan de contingencia, el cual tiene un costo estimado de S/5,100,000.00, sin embargo, para el 2022 se requiere el monto de: <br>* Pago del alquiler del local por un año (2022), S/ 1,200,000.00 <br>* Adecuación de los ambientes S/500,000.00<br>* Traslado de los archivos al nuevo local S/ 1,000,0000.00','H':2700000,'I':2700000,},
      {'A':'8','B':'NO','C':'PI - 2413312: Necrópolis de Ancón','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 09ABR2019, con el monto de inversión S/ 3,246,084.85<br> -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la elaboración del ET/ED.','G':' -Se estima que la elaboración del ET/DE se realice en 3 productos.','H':250000,'I':280000,},
      {'A':'8','B':'NO','C':'PI - 2413312: Necrópolis de Ancón','D':'ET/DE','E':'GESTIÓN','F':' * Se notificó al profesional especializado para que inicie la elaboración de términos de referencias para el ET del proyecto.','G':'La contratación de un profesional especializado para otorgar seguimiento a la elaboración del desarrollo del ET/DE','H':30000,'I':280000,},
      {'A':'9','B':'NO','C':'IOARR - 2497501: Mateo Salao (Lima)','D':'ET/DE y Ejecución física','E':'EXPEDIENTE TECNICO','F':'* Se registró la aprobación de la IOARR fue el 09SET2021, con el monto de inversión S/ 1,016,585.38.<br> -Se encuentra en proceso de elaboración de TDR para lanzar a convocatoria la elaboración del ET/ED.','G':' -Elaboración del ET/DE (se estima que la elaboración se realice en 2 productos) S/300,000.00<br>Ejecución de obra S/673,586.00<br>Supervisión S/40,000.00<br>Liquidación S/3,000.00','H':300000,'I':1016585,},
      {'A':'9','B':'NO','C':'IOARR - 2497501: Mateo Salao (Lima)','D':'ET/DE y Ejecución física','E':'INFRAESTRUCTURA','F':'* Ejecución de Obra','G':'','H':716585,'I':1016585,},
      {'A':'10','B':'SI','C':'PI - 2505984: Gran Biblioteca Pública (Lima)','D':'ET/DE','E':'GESTIÓN','F':' *  Gastos de Gestión','G':' - Implementación de la Gestión del Proyecto. Seguimiento y monitoreo','H':60000,'I':1380000,},
      {'A':'10','B':'SI','C':'PI - 2505984: Gran Biblioteca Pública (Lima)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 05ENE2021, con el monto de inversión S/ 43,696,899.89<br> * En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E. T','G':' - Elaboración de ET/DE S/1,200,000.00 y su supervisión S/ 120,000.00','H':1320000,'I':1380000,},
      {'A':'11','B':'SI','C':'PI - 2506071: Casa Hacienda Punchauca (Lima)','D':'ET/DE','E':'GESTIÓN','F':' *  Gastos de Gestión','G':' - Implementación de la Gestión del Proyecto. Seguimiento y monitoreo','H':40000,'I':543781,},
      {'A':'11','B':'SI','C':'PI - 2506071: Casa Hacienda Punchauca (Lima)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 06ENE2021, con el monto de inversión S/ 12,657,455.65<br> * En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E. T','G':' -Elaboración de ET/DE S/453,781 y su supervisión S/ 50,000.00','H':503781,'I':543781,},
      {'A':'12','B':'NO','C':'PI - 2506435: Hotel Comercio (Lima)','D':'ET/DE','E':'GESTIÓN','F':' * Se registró la declaratoria de viabilidad el 19DIC2020, con el monto de inversión S/ 19,028,874.07<br> * En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E. T','G':' - Implementación de la Gestión del Proyecto. Seguimiento y monitoreo','H':90000,'I':1231000,},
      {'A':'12','B':'NO','C':'PI - 2506435: Hotel Comercio (Lima)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':'','G':' - Elaboración de ET/DE S/ 821,000.00 y su supervisión S/ 82,100.00','H':1141000,'I':1231000,},
      {'A':'13','B':'SI','C':'PI - 2508807: I.C. (Nasca y Palpa)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 11ENE2021, con el monto de inversión S/ 23,033,381.84<br> * En proceso de mejora del TDR para lanzar a convocatoria de elaboración de PEA','G':' - Elaboración del PEA','H':487060,'I':487060,},
      {'A':'14','B':'SI','C':'PI - 2508852: Digitalización del AGN','D':'ET/DE','E':'GESTIÓN','F':' * Se registró la declaratoria de viabilidad el 13ENE2021, con el monto de inversión S/ 45,460,184.24.','G':' - Servicio de elaboración de los TdR del ET/DE S/ 30,000.00','H':30000,'I':1952716,},
      {'A':'14','B':'SI','C':'PI - 2508852: Digitalización del AGN','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * En proceso de elaboración de TDR para lanzar a convocatoria de elaboración de E. T','G':' -Elaboración del ET/DE S/ 1,922,716.00','H':1922716,'I':1952716,},
      {'A':'15','B':'SI','C':'PI - 2497434: Parque Bicentenario - Ancash','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 11SET2020, con el monto de inversión S/ 13,578,390.27','G':' *Elaboración de E. T','H':1237401,'I':1237401,},
      {'A':'16','B':'SI','C':'PI - 2499858: Parque Bicentenario - Piura','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 07OCT2020, con el monto de inversión S/ 20,882,267.86','G':' *Elaboración de E. T','H':947702,'I':947702,},
      {'A':'17','B':'SI','C':'PI - 2499997: Parque Bicentenario - Ayacucho','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 14OCT2020, con el monto de inversión S/ 30,006,599.63','G':' *Elaboración de E. T','H':530439,'I':530439,},
      {'A':'18','B':'SI','C':'PI - 2498610: Parque Bicentenario - Ucayali','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 29SET2020, con el monto de inversión S/14,286,800.50','G':' *Elaboración de E. T','H':1140582,'I':1140582,},
      {'A':'19','B':'SI','C':'PI - 2499914: Parque Bicentenario - Arequipa','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 08OCT2020, con el monto de inversión S/20,297,262.46','G':' *Elaboración de E. T','H':969509,'I':969509,},
      {'A':'20','B':'SI','C':'PI - 2498188: Parque Bicentenario - Lambayeque','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 10OCT2020, con el monto de inversión S/16,932,205.02','G':' *Elaboración de E. T','H':1008221,'I':1008221,},
      {'A':'21','B':'SI','C':'PI - 2498659: Parque Bicentenario - Loreto','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 29SET2020, con el monto de inversión S/17,299,260.64','G':' *Elaboración de E. T','H':1237401,'I':1237401,},
      {'A':'22','B':'SI','C':'PI - 2498268: Parque Bicentenario - Huanuco','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 08OCT2020, con el monto de inversión S/14,831,659,40','G':' *Elaboración de E. T','H':1237400,'I':1237400,},
      {'A':'23','B':'SI','C':'PI - 2498369: Parque Bicentenario - Apurimac','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 09OCT2020, con el monto de inversión S/20,167,137.23','G':' *Elaboración de E. T','H':1081272,'I':1081272,},
      {'A':'24','B':'SI','C':'PI - 2499921: Parque Bicentenario - Tumbes','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 08OCT2020, con el monto de inversión S/11,519,369.55','G':' *Elaboración de E. T','H':947702,'I':947702,},
      {'A':'25','B':'SI','C':'PI - 2499859: Parque Bicentenario - Ica','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 07OCT2020, con el monto de inversión S/14,105,820.39','G':' *Elaboración de E. T','H':947702,'I':947702,},
      {'A':'26','B':'SI','C':'PI - 2499288: Parque Bicentenario - Tacna','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 07OCT2020, con el monto de inversión S/14,832,554.84','G':' *Elaboración de E. T','H':956424,'I':956424,},
      {'A':'27','B':'SI','C':'PI - 2498138: Parque Bicentenario - Callao','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 30SET2020, con el monto de inversión S/20,662,539.54','G':' *Elaboración de E. T','H':1256814,'I':1256814,},
      {'A':'28','B':'SI','C':'PI - 2498147: Parque Bicentenario - La Libertad','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 30SET2020, con el monto de inversión S/14,754,954.82','G':' *Elaboración de E. T','H':934080,'I':934080,},
      {'A':'29','B':'SI','C':'PI - 2498275: Parque Bicentenario - Huancavelica','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 10OCT2020, con el monto de inversión S/15,941,850.42','G':' *Elaboración de E. T','H':1179401,'I':1179401,},
      {'A':'30','B':'SI','C':'PI - 2497468: Parque Bicentenario - Huacho (Lima)','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 12SET2020, con el monto de inversión S/15,092,412.77','G':' *Elaboración de E. T','H':934079,'I':934079,},
      {'A':'31','B':'SI','C':'PI - 2497656: Parque Bicentenario - Moquegua','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 11SET2020, con el monto de inversión S/16,332,550.60','G':' *Elaboración de E. T','H':956424,'I':956424,},
      {'A':'32','B':'SI','C':'PI - 2498259: Parque Bicentenario - Pasco','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 09OCT2020, con el monto de inversión S/14,403,937.59','G':' *Elaboración de E. T','H':1092175,'I':1092175,},
      {'A':'33','B':'SI','C':'PI - 2498370: Parque Bicentenario - Madre De Dios','D':'CAR','E':'EXPEDIENTE TECNICO','F':' *Se registró la declaratoria de viabilidad el 29SET2020, con el monto de inversión S/13,506,354.16','G':' *Elaboración de E. T','H':1237401,'I':1237401,},
      {'A':'34','B':'SI','C':'PI - 2505980: Parque Lineal Pachacamac','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 10DIC2020, con el monto de inversión S/ 24,126,075.80.<br> * Mediante el memorándum N° 001307 -2021 -OINV/MC (08SET2021), se solicita dar continuidad a la indagación de mercado para la contratación del servicio de consultoría de la elaboración del PEA.<br> * Mediante el memorándum N° 000811 -2021 -OINV/MC (23JUN2021), se remite el TDR actualizado para la contratación del servicio de consultoría de la elaboración del PEA.','G':' - Se comenzará a ejecutar la elaboración del proyecto de evaluación arqueológica (PEA), el cual comprende 7 productos en un plazo de 250 días calendarios S/1,259,939.00','H':1259939,'I':1259939,},
      {'A':'35','B':'SI','C':'PI - 2509544: Ss Culturales De Interpretación (Lima, Cusco Y Maynas - Loreto)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 13MAY2021, con el monto de inversión S/ 15,949,615.36. <br>  * Mediante el memorándum N° 001307 -2021 -OINV/MC (08SET2021), se solicita dar continuidad a la indagación de mercado para la contratación del servicio de consultoría de la elaboración del PEA. <br>  * Mediante el memorándum N° 000811 -2021 -OINV/MC (23JUN2021), se remite el TDR actualizado para la contratación del servicio de consultoría de la elaboración del PEA.','G':'Elaboración del ET/DE S/ 397,086.00','H':397086,'I':477086,},
      {'A':'35','B':'SI','C':'PI - 2509544: Ss Culturales De Interpretación (Lima, Cusco Y Maynas - Loreto)','D':'ET/DE','E':'GESTIÓN','F':' *  Gastos de Gestión','G':'Contratación de un especialista para elaboración de los TdR del ET/DE S/ 20,000.00<br>Seguimiento y monitoreo al desarrollo del ET/DE S/ 60,000.00','H':80000,'I':477086,},
      {'A':'36','B':'SI','C':'PI - 2523322: Interpr. Cultural - Teatro Municipal De Piura (Piura)','D':'ET/DE','E':'EXPEDIENTE TECNICO','F':' * Se registró la declaratoria de viabilidad el 06JUL2021, con el monto de inversión S/ 39,362,400.24.<br> * Mediante el memorándum N° 001307 -2021 -OINV/MC (08SET2021), se solicita dar continuidad a la indagación de mercado para la contratación del servicio de consultoría de la elaboración del PEA.<br> * Mediante el memorándum N° 000811 -2021 -OINV/MC (23JUN2021), se remite el TDR actualizado para la contratación del servicio de consultoría de la elaboración del PEA.','G':'Elaboración del ET/DE S/1,629,816.00','H':1629816,'I':1709816,},
      {'A':'36','B':'SI','C':'PI - 2523322: Interpr. Cultural - Teatro Municipal De Piura (Piura)','D':'ET/DE','E':'GESTIÓN','F':' *  Gastos de Gestión','G':'Contratación de un especialista para elaboración de los TdR del ET/DE S/ 20,000.00<br>Seguimiento y monitoreo al desarrollo del ET/DE S/ 60,000.00','H':80000,'I':1709816,},
      {'A':'37','B':'-','C':'Estudios de Preinversión','D':'','E':'ESTUDIOS DE PREINVERSIÓN','F':'* 16 Estudios de Preinversión','G':'­  *Elaboración de 16 Estudios de Preinversión:<br>Interpr. Cultural - Museo Amazónico (Nauta - Loreto)<br>Interpr. Cultural - Complejo Arqueo-Astronómico Chankillo (Casma - Ancash)<br>Interpr. Cultural - Monumento Chavín De Huántar (Chavín De Huántar - Ancash)<br>Centro Histórico De Tacna (Tacna)<br>Centro Histórico De Piura (Piura)<br>Centro Histórico De Cajamarca (Cajamarca)<br>Centro Histórico De Moquegua (Moquegua)<br>Interpr. Cultural - Museo Hipólito Unanue (Ayacucho)<br>Prog. Conmemoración Bicentenario De La Independencia (Lima)<br>Tambo Inga (Puente Piedra - Lima)<br>Interpr. Cultural - Museo De Sitio De Narihualá<br>Interpr. Cultural - Museo Mirador Cerro San Cristóbal (Rímac - Lima)<br>Interpr. Cultural - Museo De Sitio Huaca Pucllana<br>Interpr. Cultural - Museo Departamental San Martín<br>Interpr. Cultural - Museo Arturo Jiménez Borja (Puruchuco)<br>Museo De Sitio Wari (Pacaycasa - Ayacucho)','H':3350000,'I':3350000,},
      {'A':'TOTAL','B':'-','C':'-','D':'-','E':'-','F':'-','G':'-','H':60731948,'I':60731948,},
      

    ];
    this.inversionesBK = this.inversiones;
    this.onInit();
    console.log(this.inversiones);
  }
  onInit() {
    let bodyAnexo = document.getElementById("bodyAnexo");
    while (bodyAnexo.rows.lenght > 0) {
      bodyAnexo.deleteRow(0);
    }
    this.inversiones.forEach(inversion => {
      let fila = bodyAnexo.insertRow(bodyAnexo.rows.lenght);
      fila.insertCell(0).innerHTML = inversion.A;
      fila.insertCell(1).innerHTML = inversion.B;
      fila.insertCell(2).innerHTML = inversion.C;
      fila.insertCell(3).innerHTML = inversion.D;
      fila.insertCell(4).innerHTML = inversion.E;
      fila.insertCell(5).innerHTML = inversion.F;
      fila.insertCell(6).innerHTML = inversion.G;
      fila.insertCell(7).innerHTML = inversion.H.toLocaleString('ENG');
      fila.insertCell(8).innerHTML = inversion.I.toLocaleString('ENG');


    });
  }

}

let busqueda = new BuscarAnexo();


function myFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementById("valor");
  filter = input.value.toUpperCase();
  table = document.getElementById("bodyAnexo");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[2];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}